### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'cursor'

### ISSUE THREAD

**Issue by DortheOlsen** [3nids/quickfinder#46]
Hi

I get the following error, when refreshing a project search:

----
Traceback (most recent call last):
  File "C:/Users/efdbo/.qgis2/python/plugins\quickfinder\gui\refreshdialog.py", line 117, in refresh
    ok, message = self.projectFinder.recordSearch(search, False)
  File "C:/Users/efdbo/.qgis2/python/plugins\quickfinder\core\projectfinder.py", line 216, in recordSearch
    cur = self.conn.cursor()

AttributeError: 'NoneType' object has no attribute 'cursor'

Python-version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

QGIS-version:
2.10.1-Pisa Pisa, d20c5b7
----

Any suggestions on what's wrong?

Best regards, 
Dorthe

**Comment by alex-chaliy** [comment]
Yeah, has the same error and cannot find a solution. It would be great if somebody knows an answer.
