### ISSUE TITLE
"table quickfinder_info already exists" when creating QuickFinder file

### ISSUE THREAD

**Issue by adamczi** [3nids/quickfinder#50]
This is the error I get when I create a new QuickFinder file. The file is being created despite it. 

`Traceback (most recent call last):
  File "/home/user/.qgis2/python/plugins/quickfinder/gui/configuration_dialog.py", line 120, in create_QFTS_file
    create_FTS_file(filepath)
  File "/home/user/.qgis2/python/plugins/quickfinder/core/project_finder.py", line 56, in create_FTS_file
    cur.executescript(sql)
OperationalError: table quickfinder_info already exists`

Then when I load this file and perform a project search I get:

`Traceback (most recent call last):
  File "/home/user/.qgis2/python/plugins/quickfinder/gui/project_search_dialog.py", line 76, in process
    ok, message = self.project_finder.recordSearch(self.projectSearch)
  File "/home/user/.qgis2/python/plugins/quickfinder/core/project_finder.py", line 219, in recordSearch
    self.deleteSearch(searchId, False)
  File "/home/user/.qgis2/python/plugins/quickfinder/core/project_finder.py", line 192, in deleteSearch
    cur.execute("DELETE FROM quickfinder_data WHERE search_id = '{0}';".format(searchId))
OperationalError: no such table: quickfinder_data`

The result of search appears in the table though.

I haven't tested other functionalities.

**Comment by Bukmop89** [comment]
I've got the same problem by using sqlite database. With PostGis it work's well

**Comment by marcobra** [comment]
An error has occurred while executing Python code: 

OperationalError: table quickfinder_info already exists 
Traceback (most recent call last):
  File "/home/ubuntu/.qgis2/python/plugins/quickfinder/gui/configuration_dialog.py", line 120, in create_QFTS_file
    create_FTS_file(filepath)
  File "/home/ubuntu/.qgis2/python/plugins/quickfinder/core/project_finder.py", line 56, in create_FTS_file
    cur.executescript(sql)
OperationalError: table quickfinder_info already exists

Python version: 2.7.6 (default, Oct 26 2016, 20:33:43) [GCC 4.8.4] 
QGIS version: 2.18.2 Las Palmas, 102ee87
