### ISSUE TITLE
QGIS 2.18.25 - unable to convert a QVariant of type 0 to a QMetaType of type 2

### ISSUE THREAD

**Issue by andrerjesus** [3nids/quickfinder#69]
Cannot install QF 3.3.3 on QGIS 2.18.25

Couldn't load plugin quickfinder due to an error when calling its classFactory() method 

TypeError: unable to convert a QVariant of type 0 to a QMetaType of type 2 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python\qgis\utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/random_user/.qgis2/python/plugins\quickfinder\__init__.py", line 29, in classFactory
    return QuickFinder(iface)
  File "C:/Users/random_user/.qgis2/python/plugins\quickfinder\quickfinder_plugin.py", line 60, in __init__
    self._init_finders()
  File "C:/Users/random_user/.qgis2/python/plugins\quickfinder\quickfinder_plugin.py", line 131, in _init_finders
    self.finders['postgis'] = PostgisFinder(self)
  File "C:/Users/random_user/.qgis2/python/plugins\quickfinder\core\postgis_finder.py", line 56, in __init__
    self._searches = self.readSearches()
  File "C:/Users/random_user/.qgis2/python/plugins\quickfinder\core\postgis_finder.py", line 151, in readSearches
    priority = settings.value('priority', type=int)
TypeError: unable to convert a QVariant of type 0 to a QMetaType of type 2

Python version: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.25 Las Palmas, cbd7adecf2 

Python Path:
C:\Users\random_user\.qgis2\python\plugins\geoserverexplorer\ext-libs\httplib2-0.8-py2.7.egg
C:\Users\random_user\.qgis2\python\plugins\geoserverexplorer\ext-libs\python_dateutil-2.2-py2.7.egg
C:\Users\random_user\.qgis2\python\plugins\geoserverexplorer\ext-libs\six-1.10.0-py2.7.egg
C:\Users\random_user\.qgis2\python\plugins\geoserverexplorer\ext-libs\requests-2.5.0-py2.7.egg
C:\Users\random_user\.qgis2\python\plugins\geoserverexplorer\ext-libs\gsconfig-1.0.6-py2.7.egg
C:\Users\random_user\.qgis2\python\plugins\geoserverexplorer\ext-libs\gisdata-0.5.4-py2.7.egg
C:\Users\random_user\.qgis2\python\plugins\geoserverexplorer\ext-libs\gsimporter-1.0.0-py2.7.egg
C:\Users\random_user\.qgis2\python\plugins\geoserverexplorer\ext-libs\gsconfig-1.0.6-py2.7.egg
C:\Users\random_user\.qgis2\python\plugins\geoserverexplorer\ext-libs\gsimporter-1.0.0-py2.7.egg
C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python/plugins\processing
C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python
C:/Users/random_user/.qgis2/python
C:/Users/random_user/.qgis2/python/plugins
C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS2~1.18\bin\python27.zip
C:\PROGRA~1\QGIS2~1.18\apps\Python27\DLLs
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\plat-win
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGIS2~1.18\bin
C:\PROGRA~1\QGIS2~1.18\apps\Python27
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/random_user/.qgis2//python
C:\Users\random_user\.qgis2\python\plugins\geoserverexplorer\ext-libs

**Comment by 3nids** [comment]
I have no current plan to work on QuickFinder since it is for QGIS 2.18 only and 2.18 is almost EOL.
Please contact me if you do want to get this fixed.
